config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "/profile", to: "pages#profile"
  get "/rented", to: "pages#rented"
  post "/reservations", to: "reservations#create"
  resources :items
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
  has_many_attached :photos
  belongs_to :user
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :item
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :photo
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, only: [:new, :create, :destroy]
  include Pundit::Authorization

  # Pundit: allow-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :description, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :description, :photo])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = policy_scope(Item)
    if params[:query].present?
      sql_query = "name ILIKE :query OR category ILIKE :query"
      @items = Item.where(sql_query, query: "%#{params[:query]}%")
    else
      @items = Item.all
    end
  end

  def show
    @item = Item.find(params[:id])
    @reservation = Reservation.new
    authorize @item
    @markers = @item.geocode.map do |_item|
      {
        lat: @item.latitude,
        lng: @item.longitude
      }
    end
  end

  def new
    @item = Item.new
    authorize @item
  end

  def create
    @item = Item.new(item_params)
    @item.user = current_user
    authorize @item

    if @item.save
      redirect_to item_path(@item)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @item = Item.find(params[:id])
    authorize @item
  end

  def update
    @item = Item.find(params[:id])
    authorize @item
    @item.update(item_params)
    redirect_to item_path(@item)
  end

  def destroy
    @item = Item.find(params[:id])
    authorize @item
    @item.destroy

    redirect_to items_path
  end

  private

  def item_params
    params.require(:item).permit(:name, :description, :value, :current_situation, :category, :address, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @items = Item.all.first(3)
  end

  def profile
    @user = current_user
    @items = Item.where(user_id: @user.id)
  end

  def rented
    @reservations = Reservation.where(user_id: current_user.id)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def new
    @reservation = Reservation.new()
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.status = "pending"
    authorize @reservation

    if @reservation.save
      redirect_to items_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def reservation_params
    params.require(:reservation).permit( :item_id, :user_id, :pickup_date, :drop_date, :total_value)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/edit.html.erb
<div class="edit-card my-4">
  <h3 class="text-center">Edit Item</h3>
  <%= render "items/shared/form" %>
</div>

app/views/items/index.html.erb
<div id="index-page">

  <div class="div-for-item-bar">
    <ul class="items-bar d-flex justify-space-between">
      <li>
        <%= link_to items_path(query: "paintings") do %>
          <i class="fa-solid fa-palette"></i>
          <p>Paitings</p>
        <% end %>
      </li>
      <li>
        <%= link_to items_path(query: "sculptures") do %>
        <i class="fa-solid fa-person-walking"></i>
        <p>Sculptures</p>
        <% end %>
      </li>
      <li>
        <%= link_to items_path(query: "drawings") do %>
          <i class="fa-solid fa-pencil"></i>
          <p>Drawings</p>
        <% end %>
      </li>
      <li>
        <%= link_to items_path(query: "ceramics") do %>
          <i class="fa-solid fa-whiskey-glass"></i>
          <p>Ceramics</p>
        <% end %>
      </li>
      <li>
        <%= link_to items_path(query: "photography") do %>
          <i class="fa-solid fa-camera-retro"></i>
          <p>Photography</p>
        <% end %>
      </li>
      <li>
        <%= link_to items_path(query: "crafts") do %>
          <i class="fa-solid fa-compass-drafting"></i>
          <p>Crafts</p>
        <% end %>
      </li>
    </ul>
  </div>

  <div class="row row-cols-1 row-cols-md-4 g-4">
    <% @items.each do |item|%>
      <%= link_to item_path(item), class: "clickable-cards" do %>
        <div class="col" >
          <div class="card-art">
            <div id="carousel-<%= item.id %>" class="carousel slide" data-bs-ride="carousel">
              <div class="carousel-inner">
                <% item.photos.each do |photo| %>
                  <div class="carousel-item active">
                    <%= cl_image_tag photo.key, class:"d-block w-100", height: 200, width: 300, crop: :fill %>
                  </div>
                <% end %>
              </div>
              <button class="carousel-control-prev" type="button" data-bs-target="#carousel-<%= item.id %>" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
              </button>
              <button class="carousel-control-next" type="button" data-bs-target="#carousel-<%= item.id %>" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
              </button>
            </div>
            <div class="card-body">
              <div class= "price-btn d-flex justify-content-between">
                <p class="card-title"><%= item.name %></p>
                <p class="card-price">$ <%= item.value %></p>
              </div>
              <p class="card-text" style="overflow:scroll;height:100px;"><%= item.description %></p>
            </div>
          </div>
        </div>
      <% end %>
    <%end%>
  </div>
</div>

app/views/items/new.html.erb
<div class="edit-card my-4">
  <h3 class="text-center">New Art Piece</h3>
  <%= render "items/shared/form" %>
</div>

app/views/items/shared/_form.html.erb
<%= simple_form_for @item do |f| %>
  <%= f.input :name,
                  required: true,
                  autofocus: true %>
  <%= f.input :description,
                  required: true,
                  autofocus: true,
                  :as => :text, :input_html => { 'rows' => 10} %>
  <%= f.input :photos,
                  required: true,
                  autofocus: true,
                  as: :file, input_html: { multiple: true } %>
  <p><small>Max of 10M</small><p>
  <%= f.input :value,
                  required: true,
                  autofocus: true %>
  <%= f.input :current_situation, :as => :hidden, :input_html => { :value => "available" } %>
  <%= f.input :category,
                  required: true,
                  autofocus: true,
                  collection: ["Paintings", "Sculptures", "Drawings", "Ceramics", "Photography", "Crafts"] %>
  <div>
    <%= f.input :address,
    input_html: {data: {address_autocomplete_target: "address"}, class:"d-none"},
    wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
    %>
  </div>
  <div class="button-container">
    <%= f.button :submit, class: "btn-log-in text-center"%>
  </div>
<% end %>

app/views/items/show.html.erb
<div id= "product-page">
  <div class= "title-bar d-flex justify-content-between align-items-center my-3">
    <div class="text m-0 p-0">
      <h2 class="m-0"><%= @item.name %></h2>
    </div>
    <div class="d-flex">
      <% if @item.user == current_user %>
        <%= link_to item_path(@item), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"btn-rent" do %>
          <i class="fa-solid fa-trash"></i>
        <%end%>
        <%= link_to edit_item_path, class:"btn-rent" do %>
          <i class="fa-solid fa-pen-to-square"></i>
        <%end%>
        <a href="#" class="btn-rent"><i class="fa-solid fa-share-from-square"></i></a>
      <% else %>
        <a href="#" class="btn-rent"><i class="fa-solid fa-share-from-square"></i></a>
      <%end%>
    </div>
  </div>
  <div class="photo-details-info d-flex justify-content-between">
    <div class="left-side">
      <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
          <% @item.photos.each do |photo| %>
            <div class="carousel-item active">
              <%= cl_image_tag photo.key, class:"d-block w-100", height: 400, width: 250, crop: :fill %>
            </div>
          <% end %>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
      <div class= "container-details d-flex justify-content-between">
        <div class="container-info d-flex justify-content-between">
          <div class="item-info">
            <h3>Item's info</h3>
            <p><%= @item.description %> In pretium condimentum quam, eu pellentesque nisi dictum eu. In id leo ac quam convallis lobortis nec efficitur metus.In pretium condimentum quam, eu pellentesque nisi dictum eu. In id leo ac quam convallis lobortis nec efficitur metus.</p>
          </div>
          <div class="lessor-info">
            <h3>Lessor's info</h3>
            <p>
              <%= User.find(@item.user_id).description %>
            </p>
          </div>
        </div>
      </div>
    </div>
    <div class="right-side">
      <div class="container-book" style= "position: -webkit-sticky; position: sticky; top: var(--navigation-bar-offset, 90px) !important;;">
        <div class="date">
          <div class="input-date d-flex justify-content-between" data-controller="flatpickr">
            <div class="begin-date text-center">
              <%= simple_form_for @reservation, data: { controller: 'flatpickr' } do |f| %>
                <div class="calculation-div">
                  <%= f.input :pickup_date, as: :string, input_html: { data: { flatpickr_target: "startTime" } } %>
                  <%= f.input :drop_date, as: :string, input_html: { data: { flatpickr_target: "endTime" } } %>
                  <%= f.input :total_value, as: :hidden, input_html: { data: { flatpickr_target: "finalValue" } } %>
                </div>
                <div class="total-date text-center">
                  <p class="text">Total days</p>
                  <p data-flatpickr-target="daysLeft" value="3">0</p>
                </div>
                <div class="price">
                  <div class= "daily-price d-flex justify-content-between">
                    <p class="text">Daily price:</p>
                    <p data-flatpickr-target="itemValue">$<%= @item.value %></p>
                  </div>
                  <div class= "total-price d-flex justify-content-between">
                    <p class="text">Total price:</p>
                    <p data-flatpickr-target="totalValue">$<%= @item.value %></p>
                  </div>
                </div>
                <%= f.input :item_id, as: :hidden, input_html: { value: @item.id } %>
                <%= f.input :user_id, as: :hidden, input_html: { value: current_user.id } %>
                <%= f.submit 'Book', data: { turbo_confirm: "Are you sure you want to book this item?"}, class: "btn", style:"background-color:#1BC579; color:white; border-radius: 40px; padding: 1px 80px; margin-bottom: 10px;"%>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class= container-map>
    <div class="map-div">
      <h3 class="text-center"> Item's Location</h3>
      <div style="width: 100%; height: 400px;"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArtShare</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>

  <body>
    <%= render "layouts/shared/navbar" %>
    <%= yield %>
    <%= render "layouts/shared/footer" %>
  </body>
</html>

app/views/layouts/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    ArtShare @productions
  </div>
</div>

app/views/layouts/shared/_navbar.html.erb
<nav class="navbar sticky-top">
  <div class="container">
    <a class="navbar-brand" href="/items">
      <img src="https://res.cloudinary.com/djn023to9/image/upload/v1669213301/development/artshare_logo_clean_zgbqby.png" alt="" width="60" height="40">
    </a>
    <%= form_with url: items_path, method: :get, class: "d-flex", id:"search" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find a piece of art..."
      %>
      <%= button_tag type: 'submit', class:"btn-search" do %>
        <i class="fa-solid fa-magnifying-glass"></i>
      <% end %>
    <% end %>

    <div style="display:flex;align-items:center;">
      <%if user_signed_in? %>
        <p style="margin: auto 15px;"><%= current_user.first_name%> <%= current_user.last_name%></p>
        <li class="nav-item dropdown" style="list-style-type:none;" >
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <% if current_user.photo.attached?%>
                <%= cl_image_tag current_user.photo.key, class:"avatar", crop: :fill %>
              <% else %>
                <%= image_tag "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460__480.png", class:"avatar"%>
              <%end%>
            </a>
            <ul class="dropdown-menu dropdown-menu-lg-end" aria-labelledby="navbarDropdownMenuLink" id="dropdown-box">
              <li><%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class:"dropdown-item"%></li>
              <li><%= link_to "My Profile", profile_path, class:"dropdown-item" %></li>
              <li><%= link_to "My Rented Items", rented_path, class:"dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to "Start Renting", new_item_path, class:"dropdown-item" %></li>
            </ul>
          </li>
      <%else%>
        <%= link_to "Become a lessor", new_item_path, id:"lessor-link" %>
          <li class="nav-item dropdown" style="list-style-type:none;" id="login-icon">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="fa-regular fa-user-plus"></i>
            </a>
            <ul class="dropdown-menu dropdown-menu-lg-end" aria-labelledby="navbarDropdownMenuLink" id="dropdown-box">
              <li><%= link_to "Log In", new_user_session_path, class:"dropdown-item" %></li>
              <li><%= link_to "Register", new_user_registration_path, class:"dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to "Become a lessor", new_item_path, class:"dropdown-item" %></li>
            </ul>
          </li>
      <%end%>
    </div>
  </div>
</nav>

app/views/pages/_carousel.html.erb
<div id="carousel-<%= item.id %>" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <% item.photos.each do |photo| %>
      <div class="carousel-item active">
        <%= cl_image_tag photo.key, class:"d-block w-100", height: 200, width: 300, crop: :fill %>
      </div>
    <% end %>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carousel-<%= item.id %>" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carousel-<%= item.id %>" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
  </div>
    <div class="card-body">
      <p class="card-title"><%= item.name%></p>
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
      <div class= "d-flex justify-content-between">
        <p class="card-price">$ <%= item.value%></p>
        <a href="/items/<%=item.id%>" class="btn btn-outline-secondary" style="border-radius:20px;padding:10px">Rent</a>
      </div>
    </div>
</div>

app/views/pages/_carousel_product.html.erb
    <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel" style="width:600px">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="https://images.unsplash.com/photo-1604854574894-1be73ca43cb8?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1065&q=80" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
          <img src="https://images.unsplash.com/photo-1570877901348-07076379b061?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=987&q=80" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
          <img src="https://images.unsplash.com/photo-1610991441081-1be1a3483f13?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=997&q=80" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
          <img src="https://images.unsplash.com/photo-1515405295579-ba7b45403062?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1480&q=80" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
          <img src="https://images.unsplash.com/photo-1596120717372-f31ed4704450?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1475&q=80" class="d-block w-100" alt="...">
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
      </div>
  </div>

app/views/pages/home.html.erb
<div>

    <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1547891654-e66ed7ebb968?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80);">
      <div class="container text-center">
         <h1>Rent and lend easy from the comfort of your home!</h1>
        <p>We connect you to the best in the area, so you can give a new look to your place anytime you want!</p>
        <a class="btn btn-success" href="/users/sign_up">Join now</a>
      </div>
    </div>

    <div style="border-bottom: 1px solid rgb(184, 184, 184);padding-bottom:15px;margin-left: 20px;margin-right: 20px;">
      <div class="container d-flex" style="justify-content:space-between;">
        <div style="width:350px;margin-left:30px;">
          <h3>Spruce up your next event</h3>
          <p>Rent art to decorate your event and turn it into a memorable occasion for all attendees!</p>
        </div>

        <div style="width:350px;margin-left:50px;">
          <h3>Make your art gallery dynamic</h3>
          <p>Every visit to your gallery becomes a once-in-a-lifetime experience by rotating the art pieces exposed.</p>
        </div>

        <div style="width:350px;margin-left:50px;">
          <h3>Turn your venue into an attraction</h3>
          <p>From hotels to office buildings, all venues can become a place for art appreciation.</p>
        </div>
      </div>
    </div>
  </div>
  <div class="container" style="justify-content:space-between;">
    <div class="row row-cols-1 row-cols-md-3 g-3 position-relative m-4" style="box-shadow:0px 10px 10px -15px #111;">

      <% @items.each do |item|%>
        <%= link_to item_path(item), class: "clickable-cards" do %>
          <div class="col" >
            <div class="card-art">
              <div id="carousel-<%= item.id %>" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-inner">
                  <% item.photos.each do |photo| %>
                    <div class="carousel-item active">
                      <%= cl_image_tag photo.key, class:"d-block w-100", height: 200, width: 300, crop: :fill %>
                    </div>
                  <% end %>
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carousel-<%= item.id %>" data-bs-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carousel-<%= item.id %>" data-bs-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Next</span>
                </button>
              </div>
              <div class="card-body">
                <div class= "price-btn d-flex justify-content-between">
                  <p class="card-title"><%= item.name %></p>
                  <p class="card-price">$ <%= item.value %></p>
                </div>
                <p class="card-text" style="overflow:scroll;height:100px;"><%= item.description %></p>
              </div>
            </div>
          </div>
        <% end %>
      <%end%>
    </div>
  </div>

  <div class="container d-flex preview" style="margin-left:100px;">
    <div class="w-25 text-center">
      <h1>Rent your art</h1>
      <h2 style="margin-bottom:18px;font-size:26px;">Earn up to</h2>
      <h2 style="margin-bottom:32px;font-size:32px;"><strong>1000$</strong></h2>
      <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" style="height: 50px;">
          <div class= second-btn>
            <button class="btn btn-outline-success" type="submit" style="height: 50px;font-size: 13px;">Preview Price</button>
          </div>
        </form>
        <p style="margin-top:18px;font-size:12px;">This is an average of the product.</p>
    </div>

    <%= render "carousel_product" %>
</div>

app/views/pages/profile.html.erb
<div class="profile-page d-flex justify-content-between">
  <div class="profile-card" style= "position: -webkit-sticky; position: sticky; top: var(--navigation-bar-offset, 90px) !important;">
    <div class="id-info d-flex justify-content-between">
      <div class="img-profile">
        <% if current_user.photo.attached?%>
          <%= cl_image_tag current_user.photo.key, class:"avatar", crop: :fill %>
        <% else %>
          <%= image_tag "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460__480.png", class:"avatar"%>
        <%end%>
      </div>
      <div class="users-info">
        <h3> Hi, I'm <%= current_user.first_name %></h3>
        <p><%= @user.email %></p>
      </div>
    </div>
    <div class="user-record">
      <p class="text-center">Your info:</p>
      <div class= "my-info text-center">
        <p>
        <%= current_user.description %>
        </p>
        <a class="btn-edit text-center" type='button' href="/users/edit">Update Profile</a>
      </div>
    </div>
  </div>
  <div class="profile-items">
    <div class="categories-row d-flex justify-content-between">
      <p class="1">Item Name</p>
      <p class="2" style="margin-right:10px;">Category</p>
      <p class="3" style="margin-right:18px;">Price</p>
      <p class="4" style="margin-right:44px;">Status</p>
    </div>
    <div class="info-row" style="margin-right: 10px; margin-top: 20px;">
      <% @items.each do |item|%>
        <div class="col table-info d-flex justify-content-between text-center">
          <p style="overflow:scroll;height: 25px; width:110px;"><%= item.name %></p>
          <p style="width:110px;"><%= item.category %></p>
          <p style="width:110px;"><%= item.value %></p>
          <p style="width:110px;"><%= item.current_situation%></p>
        </div>
      <%end%>
    </div>
  </div>
</div>

app/views/pages/rented.html.erb
<div class="profile-page text-center">
<h1>My Rented Items</h1>
  <div class="rented-items" >
    <div class="categories-row d-flex justify-content-between">
      <p class="1" style="margin-left: 216px;">Item Name</p>
      <p class="2" style="margin-right: 4px;">Date</p>
      <p class="3" style="margin-right: 0px;">Total Price</p>
      <p class="4" style="margin-right: 41px;">Status</p>
    </div>
    <div class="info-row" style="margin-right: 10px; margin-top: 20px;">
      <% @reservations.each do |reservation|%>
        <div class="col table-info d-flex justify-content-between">
          <div style="width:40px;">
            <% if User.find(reservation.user_id).photo.attached?%>
              <%= cl_image_tag User.find(reservation.user_id).photo.key, class:"avatar", crop: :fill %>
            <% else %>
              <%= image_tag "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460__480.png", class:"avatar"%>
            <%end%>
          </div>
          <p style="width:110px;"><%= item_name = Item.find(reservation.item_id).name %></p>
          <p style="width:110px;"><%= reservation.pickup_date %> - <%= reservation.drop_date %></p>
          <p style="width:110px;">$<%= reservation.total_value%></p>
          <p style="width:110px;"><%= reservation.status %></p>
        </div>
      <%end%>
    </div>
  </div>
</div>